//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreClone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBaoCaoCongNo
    {
        public int MaBaoCao { get; set; }
        public int MaKH { get; set; }
        public int SoTienNoDau { get; set; }
        public int SoTienNoCuoi { get; set; }
    
        public virtual BaoCaoCongNo BaoCaoCongNo { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
