//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreClone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
        }
    
        public int MaPN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public int MaND { get; set; }
        public int GiaTriPhieuNhap { get; set; }
        public int TongSoSachNhap { get; set; }
        public int SoLoaiDauSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
