//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreClone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public int MaQuyDinh { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int SoLuongSachTonToiThieuDeNhap { get; set; }
        public int SoLuongSachNhapToiThieu { get; set; }
        public int TienNoToiDa { get; set; }
        public int SoLuongSachTonToiThieuSauKhiBan { get; set; }
        public bool DuocThuVuotSoTienKhachHangDangNo { get; set; }
    }
}
